### ISSUE TITLE
Uniqueness of encrypted values

### ISSUE THREAD

**Issue by rauanmayemir** [ioleo/cryptomute#17]
I found probably an unusual, but beautiful use case for cryptomute - generating obfuscated same length public ids from a serial integer.

However, it's not written anywhere so I wanted to ask if there is a uniqueness guarantee given that max range value is big enough?

(I'm not concerned with the security of encrypted values, just its uniqueness for a unique set of numbers)

**Comment by ioleo** [comment]
This is a two-way encryption, meaning you can recover the original value given you know the key and IV (for some algorithms). Now, let's consider what it would mean if the mapping would not yield unique results?
Basically it would render the whole algorithm useless, as in case of ambigous values you would not be able to deterministically recover the original value.
